import { projectItem } from './../node-api/index';
import { defineStore } from 'pinia';
const projectList: projectItem[] = [
	{
		id: 'x002-4-1',
		name: 'x002-4',
		host: 'X002-4',
		ip: '172.16.2.152',
		port: '22',
		memory: '2.2/4G',
		disk: '80% of 256G',
		rcs_commit: 'RCS commit',
		allow_rcs_rollback: true,
		allow_rcs_version_update: true,
		allow_dispatch_version_update: true,
		allow_rcs_restart: true,
		allow_wcs_restart: true,
		allow_dispatch_restart: true,
	},
	{
		id: 'x002-5-1',
		name: 'x002-5',
		host: 'X002-5',
		ip: '172.16.2.153',
		port: '22',
		memory: '2.2/4G',
		disk: '80% of 256G',
		rcs_commit: 'RCS commit',
		allow_rcs_rollback: true,
		allow_rcs_version_update: true,
		allow_dispatch_version_update: true,
		allow_rcs_restart: true,
		allow_wcs_restart: true,
		allow_dispatch_restart: true,
	},
	{
		id: 'newsort',
		name: 'NEWSORT',
		host: 'NEWSORT',
		ip: '10.0.66.108',
		port: '22',
		memory: '2.2/4G',
		disk: '80% of 256G',
		rcs_commit: 'RCS commit',
		allow_rcs_rollback: true,
		allow_rcs_version_update: true,
		allow_dispatch_version_update: true,
		allow_rcs_restart: false,
		allow_wcs_restart: true,
		allow_dispatch_restart: true,
	},
	{
		id: 'test2',
		name: 'TEST2',
		host: 'TEST2',
		ip: '47.104.247.29',
		port: '6624',
		memory: '2.2/4G',
		disk: '80% of 256G',
		rcs_commit: 'RCS commit',
		allow_rcs_rollback: true,
		allow_rcs_version_update: true,
		allow_dispatch_version_update: true,
		allow_rcs_restart: false,
		allow_wcs_restart: true,
		allow_dispatch_restart: true,
	},
	{
		id: 'jd002',
		name: 'JD002',
		host: 'JD002',
		ip: '47.104.247.29',
		port: '6413',
		memory: '2.2/4G',
		disk: '80% of 256G',
		rcs_commit: 'RCS commit',
		allow_rcs_rollback: true,
		allow_rcs_version_update: true,
		allow_dispatch_version_update: true,
		allow_rcs_restart: false,
		allow_wcs_restart: true,
		allow_dispatch_restart: true,
	},
	{
		id: 'jp015-1',
		name: 'JP015-1',
		host: 'JP015-1',
		ip: '47.104.247.29',
		port: '6773',
		memory: '2.2/4G',
		disk: '80% of 256G',
		rcs_commit: 'RCS commit',
		allow_rcs_rollback: true,
		allow_rcs_version_update: true,
		allow_dispatch_version_update: true,
		allow_rcs_restart: false,
		allow_wcs_restart: true,
		allow_dispatch_restart: true,
	},

];
export const useRemoteConfigStore = defineStore('remoteConfig', {
	state: () => ({
		projectList
	}),
	getters: {
	},
	actions: {
	},
});